#include "hal_data.h"
#include "loader_table.h"
#include <stdlib.h>
#include <wolfssl/wolfcrypt/ecc.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

extern bsp_leds_t g_bsp_leds;
extern void bsp_copy_4byte(uint32_t *src, uint32_t *dst, uint32_t bytesize);
extern const loader_table table[TABLE_ENTRY_NUM];

void  dummy_loader();
int loader_main(void);

void dummy_loader()
{
    uint8_t table_num;

         void (*app_prg)(void);
         /* LED type structure */
         bsp_leds_t leds = g_bsp_leds;
         /* If this board has no LEDs then trap here */
         if (0 == leds.led_count)
         {
             while (1)
             {
                 ;                          // There are no LEDs on this board
             }
         }
         /* Holds level to set for pins */
         bsp_io_level_t pin_level = BSP_IO_LEVEL_HIGH;

         /* Unprotect I/O port registers */
         R_BSP_PinAccessEnable();

         /* Turn on LED0: Indicate application program copy start */
         R_BSP_PinWrite((bsp_io_port_pin_t) leds.p_leds[BSP_LED_RLED0], pin_level);

         R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);

         /* Copy application program with parameter in loader table. */
         /* In this sample, application program is copied from Flash memory to System SRAM.*/
         for ( table_num = 0; table_num < TABLE_ENTRY_NUM; table_num++)
         {
           if (table[table_num].enable_flag == TABLE_ENABLE)
           {
             bsp_copy_4byte(table[table_num].src, table[table_num].dst, table[table_num].size);
           }
         }

         /* Ensuring data-changing */
         __asm volatile("dsb");

         /* Turn on LED3: Indicate application program copy end */
         R_BSP_PinWrite((bsp_io_port_pin_t) leds.p_leds[BSP_LED_RLED3], pin_level);

         /* Protect I/O port registers */
         R_BSP_PinAccessDisable();

         /* Delay */
         R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);

         /* Set application program destination to app_prg */
         //app_prg = (void(*)(void))table[0].dst;
         // 0x10010674 can be found in app.map, local_system_init()
         // e.g
         //.text.local_system_init
         //0x10010674       0x30 ./src/local_system_init.o
         //0x10010674                local_system_init
         app_prg = (void(*))(0x10010228);
         /* Jump to the application project */
         app_prg();
}
/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
#if 0
    dummy_loader();
#else
    loader_main();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}
